In [22]:
import torch
hd = 4
freq_seq = torch.arange(hd)
print(freq_seq)
inv_freq = 1.0 / (10000 ** (freq_seq / hd))
print(inv_freq)
pos = torch.arange(5)
print(pos)

theta = torch.outer(pos, inv_freq)

print(theta)
print(theta.size())
x = theta.unsqueeze(0).unsqueeze(2)
print(x.size())

xx = torch.repeat_interleave(theta, 2, dim=-1)
yy = torch.repeat_interleave(x, 2, dim=-1)
print(xx.size())
print(yy)


tensor([0, 1, 2, 3])
tensor([1.0000, 0.1000, 0.0100, 0.0010])
tensor([0, 1, 2, 3, 4])
tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.0000e+00, 1.0000e-01, 1.0000e-02, 1.0000e-03],
        [2.0000e+00, 2.0000e-01, 2.0000e-02, 2.0000e-03],
        [3.0000e+00, 3.0000e-01, 3.0000e-02, 3.0000e-03],
        [4.0000e+00, 4.0000e-01, 4.0000e-02, 4.0000e-03]])
torch.Size([5, 4])
torch.Size([1, 5, 1, 4])
torch.Size([5, 8])
tensor([[[[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
           0.0000e+00, 0.0000e+00, 0.0000e+00]],

         [[1.0000e+00, 1.0000e+00, 1.0000e-01, 1.0000e-01, 1.0000e-02,
           1.0000e-02, 1.0000e-03, 1.0000e-03]],

         [[2.0000e+00, 2.0000e+00, 2.0000e-01, 2.0000e-01, 2.0000e-02,
           2.0000e-02, 2.0000e-03, 2.0000e-03]],

         [[3.0000e+00, 3.0000e+00, 3.0000e-01, 3.0000e-01, 3.0000e-02,
           3.0000e-02, 3.0000e-03, 3.0000e-03]],

         [[4.0000e+00, 4.0000e+00, 4.0000e-01, 4.0000e-01, 4.0000e-02,
     

In [ ]:
print(yy.size())
yy1 = yy[..., ::2]
yy2 = yy[..., 1::2]
print(yy1.size())
print(yy2.size())

yy3 = torch.stack((yy1, yy2), dim=-1)
print(yy3.size())

torch.Size([1, 5, 1, 8])
torch.Size([1, 5, 1, 4])
torch.Size([1, 5, 1, 4])
torch.Size([2, 1, 5, 1, 4])
